package sqlworkbench

import (
	"fmt"
	"strings"

	"github.com/ealink1/super-link/internal/domain"
	"github.com/ealink1/super-link/internal/upstream/connection"
)

func CanCreateTable(dialect string) bool { return structureDialect(dialect) != "" }

// CreateTableSQL builds a bounded, validated definition from designer fields.
func CreateTableSQL(dialect string, object domain.Object, columns []connection.ColumnDefinition) (string, error) {
	kind := structureDialect(dialect)
	if kind == "" {
		return "", fmt.Errorf("此数据库暂不支持可视化建表")
	}
	if strings.TrimSpace(object.Name) == "" || len(columns) == 0 || len(columns) > 1024 {
		return "", fmt.Errorf("请填写表名和 1–1024 个字段")
	}
	table, err := ObjectName(dialect, object)
	if err != nil {
		return "", err
	}
	primary := []string{}
	seen := map[string]bool{}
	for _, c := range columns {
		if strings.TrimSpace(c.Name) == "" || seen[strings.ToLower(c.Name)] {
			return "", fmt.Errorf("字段名称不能为空或重复：%s", c.Name)
		}
		seen[strings.ToLower(c.Name)] = true
		if c.Key != "" && c.Key != "PRI" {
			return "", fmt.Errorf("仅支持主键，请在建表后添加其他索引")
		}
		if c.Key == "PRI" {
			q, e := Quote(dialect, c.Name)
			if e != nil {
				return "", e
			}
			primary = append(primary, q)
		}
	}
	definitions, comments := []string{}, []string{}
	autoCount := 0
	inlinePrimary := false
	for _, c := range columns {
		extra := strings.ToLower(strings.TrimSpace(c.Extra))
		if extra != "" && extra != "auto_increment" {
			return "", fmt.Errorf("不支持的字段属性：%s", c.Name)
		}
		auto := extra == "auto_increment"
		if auto {
			autoCount++
			typ := strings.ToUpper(strings.TrimSpace(c.Type))
			integer := typ == "INT" || typ == "INTEGER" || typ == "BIGINT" || typ == "SMALLINT" || (kind == "mysql" && (typ == "TINYINT" || typ == "MEDIUMINT" || typ == "INT UNSIGNED" || typ == "BIGINT UNSIGNED"))
			if !integer || c.Key != "PRI" || len(primary) != 1 || c.HasDefault {
				return "", fmt.Errorf("自增字段必须为整数类型、单列主键且没有默认值：%s", c.Name)
			}
			if kind == "sqlite" && typ != "INTEGER" {
				return "", fmt.Errorf("SQLite 自增主键必须使用 INTEGER 类型")
			}
		}
		if c.Key == "PRI" {
			c.Nullable = "NO"
		}
		definition, e := columnDefinition(kind, c, connection.ColumnDefinition{})
		if e != nil {
			return "", fmt.Errorf("字段 %s：%w", c.Name, e)
		}
		if auto && kind == "postgres" {
			definition += " GENERATED BY DEFAULT AS IDENTITY"
		}
		if auto && kind == "sqlite" {
			definition += " PRIMARY KEY AUTOINCREMENT"
			inlinePrimary = true
		}
		if c.Comment != "" && kind == "postgres" {
			q, _ := Quote(dialect, c.Name)
			comments = append(comments, "COMMENT ON COLUMN "+table+"."+q+" IS "+TextLiteral(kind, c.Comment)+";")
		}
		if c.Comment != "" && kind == "sqlite" {
			return "", fmt.Errorf("SQLite 不支持字段注释，请清空注释：%s", c.Name)
		}
		definitions = append(definitions, definition)
	}
	if autoCount > 1 {
		return "", fmt.Errorf("只能设置一个自增字段")
	}
	if len(primary) > 0 && !inlinePrimary {
		definitions = append(definitions, "PRIMARY KEY ("+strings.Join(primary, ", ")+")")
	}
	sql := "CREATE TABLE " + table + " (\n  " + strings.Join(definitions, ",\n  ") + "\n);"
	if len(comments) > 0 {
		sql += "\n" + strings.Join(comments, "\n")
	}
	return sql, nil
}
