package sqlworkbench

import (
	"database/sql"
	_ "modernc.org/sqlite"
	"strings"
	"testing"

	"github.com/ealink1/super-link/internal/domain"
	"github.com/ealink1/super-link/internal/upstream/connection"
)

func TestCreateTableDialectDefinitions(t *testing.T) {
	for _, tc := range []struct{ dialect, fragment string }{
		{"mysql", "AUTO_INCREMENT"}, {"postgres", "GENERATED BY DEFAULT AS IDENTITY"}, {"sqlite", "PRIMARY KEY AUTOINCREMENT"},
	} {
		t.Run(tc.dialect, func(t *testing.T) {
			sql, err := CreateTableSQL(tc.dialect, domain.Object{Name: "order.details", Scope: "demo"}, []connection.ColumnDefinition{{Name: "id", Type: "INTEGER", Nullable: "NO", Key: "PRI", Extra: "auto_increment"}, {Name: "value", Type: "TEXT", Nullable: "YES"}})
			if err != nil || !strings.Contains(sql, tc.fragment) || strings.Count(sql, "PRIMARY KEY") != 1 {
				t.Fatalf("invalid definition: %s / %v", sql, err)
			}
			if tc.dialect == "mysql" && !strings.Contains(sql, "`demo`.`order.details`") {
				t.Fatal(sql)
			}
		})
	}
	sql, err := CreateTableSQL("postgres", domain.Object{Name: "t", Schema: "literal.schema"}, []connection.ColumnDefinition{{Name: "v", Type: "TEXT", Nullable: "YES", Comment: "it's useful"}})
	if err != nil || !strings.Contains(sql, `"literal.schema"."t"`) || !strings.Contains(sql, "'it''s useful'") {
		t.Fatal(sql, err)
	}
}

func TestCreateTableRejectsInvalidDefinitions(t *testing.T) {
	base := connection.ColumnDefinition{Name: "id", Type: "INTEGER", Nullable: "NO", Key: "PRI"}
	cases := [][]connection.ColumnDefinition{nil, {base, base}}
	for _, edit := range []func(*connection.ColumnDefinition){
		func(c *connection.ColumnDefinition) { c.Name = " " },
		func(c *connection.ColumnDefinition) { c.Type = "INT); DROP TABLE x; --" },
		func(c *connection.ColumnDefinition) { c.Extra = "generated" },
		func(c *connection.ColumnDefinition) { c.Extra = "auto_increment"; c.Type = "TEXT" },
		func(c *connection.ColumnDefinition) { v := "1; DROP TABLE x"; c.Default = &v; c.HasDefault = true },
	} {
		c := base
		edit(&c)
		cases = append(cases, []connection.ColumnDefinition{c})
	}
	for _, columns := range cases {
		if sql, err := CreateTableSQL("mysql", domain.Object{Name: "t"}, columns); err == nil {
			t.Fatalf("accepted invalid fields: %s", sql)
		}
	}
	if CanCreateTable("redis") {
		t.Fatal("non SQL creation enabled")
	}
}

func TestCreateTableSQLiteActualExecution(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	text, err := CreateTableSQL("sqlite", domain.Object{Name: "order.details"}, []connection.ColumnDefinition{{Name: "id", Type: "INTEGER", Nullable: "NO", Key: "PRI", Extra: "auto_increment"}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err = db.Exec(text); err != nil {
		t.Fatal(err)
	}
	if _, err = db.Exec(`INSERT INTO "order.details" DEFAULT VALUES`); err != nil {
		t.Fatal(err)
	}
	var id int
	if err = db.QueryRow(`SELECT id FROM "order.details"`).Scan(&id); err != nil || id != 1 {
		t.Fatal(id, err)
	}
}
